# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkjQ4mlPVEJAumSIRpnO0AhA1ZED6kf4
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers sentencepiece gtts

import torch
import torch.nn as nn
import torchvision.models as models
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights

from torchvision import transforms
from PIL import Image

import matplotlib.pyplot as plt
import numpy as np

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

from google.colab import files

from gtts import gTTS
from IPython.display import Audio

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

class Attention(nn.Module):
    def __init__(self, encoder_dim, decoder_dim, attention_dim):
        super(Attention, self).__init__()

        self.encoder_att = nn.Linear(encoder_dim, attention_dim)
        self.decoder_att = nn.Linear(decoder_dim, attention_dim)
        self.full_att = nn.Linear(attention_dim, 1)

        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)

    def forward(self, encoder_out, decoder_hidden):

        att1 = self.encoder_att(encoder_out)
        att2 = self.decoder_att(decoder_hidden).unsqueeze(1)

        att = self.full_att(self.relu(att1 + att2)).squeeze(2)

        alpha = self.softmax(att)

        context = (encoder_out * alpha.unsqueeze(2)).sum(dim=1)

        return context, alpha

class DecoderWithAttention(nn.Module):
    def __init__(self, attention_dim, embed_dim, decoder_dim, vocab_size, encoder_dim=2048, dropout=0.5):
        super(DecoderWithAttention, self).__init__()

        self.attention = Attention(encoder_dim, decoder_dim, attention_dim)

        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTMCell(embed_dim + encoder_dim, decoder_dim)

        self.fc = nn.Linear(decoder_dim, vocab_size)

        self.init_h = nn.Linear(encoder_dim, decoder_dim)
        self.init_c = nn.Linear(encoder_dim, decoder_dim)

        self.relu = nn.ReLU()

    def init_hidden_state(self, encoder_out):
        mean_encoder = encoder_out.mean(dim=1)
        h = self.init_h(mean_encoder)
        c = self.init_c(mean_encoder)
        return h, c

    def forward(self, encoder_out, captions, lengths):

      batch_size = encoder_out.size(0)
      vocab_size = self.fc.out_features
      max_length = max(lengths)

      h, c = self.init_hidden_state(encoder_out)

      embeddings = self.dropout(self.embedding(captions))

      outputs = torch.zeros(batch_size, max_length, vocab_size).to(captions.device)

      for t in range(max_length):

        batch_size_t = sum([l > t for l in lengths])

        context, alpha = self.attention(
            encoder_out[:batch_size_t],
            h[:batch_size_t]
        )

        lstm_input = torch.cat(
            [embeddings[:batch_size_t, t, :], context],
            dim=1
        )

        h_t, c_t = self.lstm(
            lstm_input,
            (h[:batch_size_t], c[:batch_size_t])
        )

        preds = self.fc(self.dropout(h_t))

        outputs[:batch_size_t, t, :] = preds

        h = torch.cat([h_t, h[batch_size_t:]], dim=0)
        c = torch.cat([c_t, c[batch_size_t:]], dim=0)

      return outputs

weights = EfficientNet_B0_Weights.DEFAULT

resnet = efficientnet_b0(weights=weights)

modules = list(resnet.children())[:-2]

resnet_encoder = nn.Sequential(*modules)

checkpoint = torch.load(
    "/content/drive/MyDrive/image_caption_model.pth",
    map_location=device
)

word2idx = checkpoint["word2idx"]
idx2word = checkpoint["idx2word"]

attention_dim = checkpoint["attention_dim"]
embed_dim = checkpoint["embed_dim"]
decoder_dim = checkpoint["decoder_dim"]
encoder_dim = checkpoint["encoder_dim"]

decoder = DecoderWithAttention(
    attention_dim=attention_dim,
    embed_dim=embed_dim,
    decoder_dim=decoder_dim,
    vocab_size=len(word2idx),
    encoder_dim=encoder_dim
)

resnet_encoder.load_state_dict(
    checkpoint["encoder_state_dict"]
)

decoder.load_state_dict(
    checkpoint["decoder_state_dict"]
)

resnet_encoder = resnet_encoder.to(device)
decoder = decoder.to(device)

resnet_encoder.eval()
decoder.eval()

print("Model Loaded Successfully!")

uploaded = files.upload()

image_name = list(uploaded.keys())[0]

image = Image.open(image_name).convert("RGB")

plt.imshow(image)
plt.axis("off")
plt.show()

img_tensor = transform(image)

def generate_caption_beam(image, beam_size=7, max_length=36):

    decoder.eval()
    resnet_encoder.eval()

    image = image.unsqueeze(0).to(device)

    with torch.no_grad():
        features = resnet_encoder(image)

    batch_size = features.size(0)
    encoder_dim = features.size(1)


    features = features.view(batch_size, encoder_dim, -1)
    features = features.permute(0, 2, 1)


    h, c = decoder.init_hidden_state(features)


    start_token = word2idx['<start>']


    sequences = [[ [start_token], 0.0, h, c ]]
    completed_sequences = []

    for _ in range(max_length):
        all_candidates = []
        for seq, score, h, c in sequences:


            if seq[-1] == word2idx['<end>']:
                completed_sequences.append((seq, score))
                continue


            word = torch.tensor([seq[-1]]).to(device)
            embedding = decoder.embedding(word)


            context, alpha = decoder.attention(features, h)


            lstm_input = torch.cat([embedding.squeeze(1), context], dim=1)
            h_new, c_new = decoder.lstm(lstm_input, (h, c))


            output = decoder.fc(h_new)
            log_probs = torch.log_softmax(output, dim=1)


            top_log_probs, top_indices = torch.topk(log_probs, beam_size)

            for i in range(beam_size):
                next_word = top_indices[0][i].item()
                next_score = score + top_log_probs[0][i].item()
                candidate = [seq + [next_word], next_score, h_new, c_new]
                all_candidates.append(candidate)


        sequences = sorted(all_candidates, key=lambda tup: tup[1], reverse=True)
        sequences = sequences[:beam_size]


        if len(completed_sequences) >= beam_size:
            break


    if len(completed_sequences) == 0:
        completed_sequences = sequences


    best_seq = sorted(completed_sequences, key=lambda tup: tup[1], reverse=True)[0][0]


    caption = [idx2word[idx] for idx in best_seq if idx2word[idx] not in ('<start>', '<end>')]

    return caption

model_name = "facebook/nllb-200-distilled-600M"

nllb_tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    use_fast=False,
    src_lang="eng_Latn"
)

nllb_model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)

def translate_hindi(text):
    inputs = nllb_tokenizer(
        text,
        return_tensors="pt",
        src_lang="eng_Latn"
    ).to(device)

    with torch.no_grad():
        output = nllb_model.generate(
            **inputs,
            forced_bos_token_id=nllb_tokenizer.convert_tokens_to_ids("hin_Deva"),
            max_length=100,
            num_beams=5
        )

    return nllb_tokenizer.decode(output[0], skip_special_tokens=True)

def translate_marathi(text):
    inputs = nllb_tokenizer(
        text,
        return_tensors="pt",
        src_lang="eng_Latn"
    ).to(device)

    with torch.no_grad():
        output = nllb_model.generate(
            **inputs,
            forced_bos_token_id=nllb_tokenizer.convert_tokens_to_ids("mar_Deva"),
            max_length=100,
            num_beams=5
        )

    return nllb_tokenizer.decode(output[0], skip_special_tokens=True)

caption = generate_caption_beam(img_tensor, beam_size=7)

english_caption = " ".join(caption)

print("English :", english_caption)

hindi_caption = translate_hindi(english_caption)

marathi_caption = translate_marathi(english_caption)

print("Hindi :", hindi_caption)
print("Marathi :", marathi_caption)

tts_en = gTTS(text=english_caption, lang='en')
tts_en.save("english.mp3")

tts_hi = gTTS(text=hindi_caption, lang='hi')
tts_hi.save("hindi.mp3")

tts_mr = gTTS(text=marathi_caption, lang='mr')
tts_mr.save("marathi.mp3")

print("English Audio")
Audio("english.mp3")

print("Hindi Audio")
Audio("hindi.mp3")

print("Marathi Audio")
Audio("marathi.mp3")





